Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -21,8 +21,8 @@ jobs:
       # Run each check
       - name: Check if a branch other than develop is being merged to master
         shell: bash
-        run: if [ $GITHUB_HEAD_REF != "develop" ] && [ $GITHUB_BASE_REF = "master" ]; then echo "::error No branch other than develop can be merged to master. Your base branch is $GITHUB_BASE_REF and head branch is $GITHUB_HEAD_REF" && exit 1; else echo "::notice check successful"; fi
+        run: if [ $GITHUB_HEAD_REF != "develop" ] && [ $GITHUB_BASE_REF = "master" ]; then echo "::error No branch other than develop can be merged to master. Please update the base branch" && exit 1; else echo "::notice check successful"; fi
 
-      - name: Check if a branch master is being merged to any other branch
+      - name: Check if master branch is being merged to any other branch
         shell: bash
         run: if [ $GITHUB_HEAD_REF = "master" ]; then echo "::error Master branch cannot be merged to any other branch." && exit 1; else echo "::notice check successful" ; fi
