Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -24,4 +24,4 @@ jobs:
 
       - name: Check if a branch master is merged to any other branch
         shell: bash
-        run: if [ $GITHUB_HEAD_REF = "master" ]; then echo "::notice check successful"; else echo "::error Master branch cannot be merged to any other branch." && exit 1 ; fi
+        run: if [ $GITHUB_HEAD_REF = "master" ]; then echo "::error Master branch cannot be merged to any other branch."; else echo "::notice check successful" && exit 1 ; fi
